apiVersion: v1
kind: Service
metadata:
  name: cluster-mgmt-service
spec:
  type: NodePort
  ports:
  - port: 9001
    targetPort: 9000
    nodePort: 30001
    protocol: TCP
    name: http
  selector:
    name: cluster-mgmt-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-mgmt-service-deployment
spec:
  selector:
    matchLabels:
      name: cluster-mgmt-service
  replicas: 1
  template:
    metadata:
      labels:
        name: cluster-mgmt-service
    spec:
      containers:
       - name: cluster-mgmt-service
         image: cratekube/cluster-mgmt-service:latest
         ports:
         - containerPort: 9000
         volumeMounts:
         - mountPath: /app/kube/cratekube_rsa
           name: rke-ssh-volume
         - mountPath: /app/config/
           name: config-volume
         env:
         - name: RKE_PRIVATE_KEY_PATH
           value: /app/kube/cratekube_rsa
         - name: RKE_NODE_USER
           value: ec2-user
         - name: ADMIN_APIKEY
           valueFrom:
            secretKeyRef:
             name: cratekube-api-secret
             key: admin-api-key
      volumes:
       - name: rke-ssh-volume
         hostPath:
          path: /var/lib/cratekube/cratekube_rsa
       - name: config-volume
         hostPath:
          path: /var/lib/cratekube/cluster-mgmt-service/config/
